### ISSUE TITLE
New update doesn't show GPU Usage

### ISSUE THREAD

**Issue by limapedro** [microsoft/tensorflow-directml#134]
I was running the new update (tensorflow-directml 1.15.4.dev201216) and notice that I can't see how much of the GPU is being used, performance got a little bit worse, about 8% slower, it seems to be the case the Windows doesn't recognize this version on the GPU Engine.

tensorflow-directml 1.15.4.dev201216  GPU Usage

![Screenshot (79)](https://user-images.githubusercontent.com/16644771/102829975-0f595e00-43c7-11eb-9df3-42b7649b37b7.png)

tensorflow-directml 1.15.3.dev200911 GPU Usage

![Screenshot (81)](https://user-images.githubusercontent.com/16644771/102830032-2ef08680-43c7-11eb-8eb2-af3dbf007176.png)

Happy Christmas and New Year everyone!!

**Comment by jstoecker** [comment]
We made a change in 201216 that [places work on the compute queue](https://github.com/microsoft/tensorflow-directml/pull/102) instead of the 3D/graphics queue (for AMD devices only). You'll see this if you open one of the "Compute" panels  in the Performance tab. The red area of the 3D panel shows running tensorflow-directml.1.15.3.dev200911, and the blue area of the Compute 0 panel shows running tensorflow-directml.1.15.4.dev201216:

![image](https://user-images.githubusercontent.com/3835701/103586145-505a7380-4e99-11eb-8837-0f052e054efa.png)

Curiously, the "GPU" column you're showing doesn't seem to be showing the work happening in the compute queue. I'm not sure if this is a bug or not, but I'll see what I can find. Regardless, rest assured the work is actually running on the graphics card. :)

Thanks for testing it out, and I hope you enjoyed the holidays. :)

**Comment by jstoecker** [comment]
To follow up, what you see under the "GPU" column or as the "Utilization" will be the highest percentage from one of the four preselected engines in the performance tab: 3D, Copy, Video Encode, and Video Decode. Since the Compute engines are not displayed by default, they do not contribute to the reported utilization. I'm told this behavior _may_ change in the future so that the Compute engine replaces the Copy engine as one of the 4 defaults.

For now, I suggest looking at the performance tab and ensuring the compute engine is displayed if you want to see this metric. Technically this shows the utilization for all processes, but not many processes use the compute engine (unlike, say, the 3D engine) so it's likely to be just TFDML work in most cases. These are all pretty high-level measurements though, so a dedicated GPU profiling tool is the way to go if you really want to dive deeper.

**Comment by limapedro** [comment]
@jstoecker Thank you for the reply, I see that things are a bit different now, I knew it as computing, but I wanted to check the GPU utilization in the task manager. Thanks again.
