### ISSUE TITLE
why /DML:0 instead of /GPU:0 ?

### ISSUE THREAD

**Issue by iperov** [microsoft/tensorflow-directml#225]
Can you explain the logic behind this decision?

If I run any github tensorflow project, it requires to rename all /GPU to /DML. Not convenient.

**Comment by jstoecker** [comment]
Yeah, it's a discussion we had and there isn't a perfect solution. A few reasons:

- Some third-party scripts use the presence of a "GPU" device to mean the presence of CUDA and use CUDA-specific operators (e.g. CuDNNLSTM) that don't even have CPU implementations.
- Some internal TF runtime code uses "GPU" to mean CUDA and do CUDA-specific optimizations.
- Using "GPU" would prevent DML from coexisting with other backends. This may be more important when we move to TF2 if things transition to a more modular device backend.

**Comment by ghost** [comment]
(Firstly, thanks for this excellent project!)
This issue is about the cost of migrating form existing TensorFlow project to TensorFlow-DirectML.

Related question: When migrating form existing TF project, is it as easy as changing the device placement from `/GPU:0` to `/DML:0`? Is there any other code which needs to be modified?
And, is there any **"Brief Migration Guideline"**?

(Currently I don't own a suitable graphic card for DirectML, so sorry that I can't test it by myself. But I'm sure that many developers are also wondering about the migration cost.)

**Comment by wchao1115** [comment]
DirectML should work in most DirectX12-capable graphics cards. I want to also point out that for an existing script that doesn't explicitly request a /GPU device and that it doesn't have a strong dependency on any explicit cuDNN kernel, and simply opt for the default behavior, TensorFlow-DirectML defaults to /DML. There were some active discussion in the TensorFlow community at one point about overloading /GPU for a different backend in the context of TF2 pluggable device. But I believe the decision was to not mess with what people already use and risk breaking their expectation.

**Comment by ghost** [comment]
Thanks for detailed reply!
