### ISSUE TITLE
It's not working on Intel Graphics 5500

### ISSUE THREAD

**Issue by sabbir2609** [microsoft/tensorflow-directml#398]
OS : Windows 10
Python version  : 3.9.15
tensorflow-cpu==2.10.0

when I run `import tensorflow as tf`
it shows 0 compatible device

**Comment by PatriceVignola** [comment]
When importing tensorflow, we check that the hardware satisfies the 2 following minimum requirements:
1. Supports all datatypes between 8 and 32 bits
2. Is able to run the simplest DirectML operator (Identity) without any errors

If the enumeration shows 0 compatible devices, it's probably because one of the 2 requirements has failed.
